sudo: required

language: c

env:
  - BUILD_DIR=.

services:
  - docker

before_install:
  - docker build -t siomiz/searx $BUILD_DIR

install: true

script:
  - docker run siomiz/searx echo "[Travis CI OK]"
